/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2019-10-24 19:50:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.juddi.v3.client.UDDIConstants;
import org.apache.juddi.webconsole.hub.UddiHub;
import org.apache.juddi.api_v3.Node;
import java.util.List;
import org.apache.juddi.webconsole.hub.UddiHub;
import org.apache.juddi.webconsole.resources.ResourceLoader;
import org.apache.juddi.webconsole.hub.UddiHub;
import org.apache.juddi.webconsole.resources.ResourceLoader;
import org.apache.juddi.webconsole.CrossSiteRequestForgeryException;
import org.apache.juddi.webconsole.hub.UddiHub;
import org.apache.juddi.webconsole.hub.UddiHub;
import org.apache.juddi.webconsole.resources.ResourceLoader;
import org.apache.commons.lang.StringEscapeUtils;
import org.apache.juddi.webconsole.resources.ResourceLoader;
import org.apache.juddi.webconsole.hub.UddiHub;
import org.apache.commons.lang.StringEscapeUtils;
import java.io.IOException;
import java.util.jar.Attributes;
import java.util.jar.Manifest;
import java.io.InputStream;
import java.util.jar.JarFile;
import java.net.URL;
import java.util.Enumeration;
import org.apache.juddi.webconsole.resources.ResourceLoader;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/user/banner.jsp", Long.valueOf(1571940171822L));
    _jspx_dependants.put("/csrf.jsp", Long.valueOf(1571940153352L));
    _jspx_dependants.put("/header-top.jsp", Long.valueOf(1571940153780L));
    _jspx_dependants.put("/login.jsp", Long.valueOf(1571940155202L));
    _jspx_dependants.put("/autoLogoutModal.jsp", Long.valueOf(1571940154013L));
    _jspx_dependants.put("/header-bottom.jsp", Long.valueOf(1571940158188L));
    _jspx_dependants.put("/tmodelChooser.jsp", Long.valueOf(1571940159213L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.jar.Manifest");
    _jspx_imports_classes.add("org.apache.juddi.webconsole.CrossSiteRequestForgeryException");
    _jspx_imports_classes.add("java.util.Enumeration");
    _jspx_imports_classes.add("java.net.URL");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("java.util.jar.JarFile");
    _jspx_imports_classes.add("org.apache.juddi.api_v3.Node");
    _jspx_imports_classes.add("java.util.jar.Attributes");
    _jspx_imports_classes.add("org.apache.juddi.v3.client.UDDIConstants");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.apache.juddi.webconsole.resources.ResourceLoader");
    _jspx_imports_classes.add("org.apache.juddi.webconsole.hub.UddiHub");
    _jspx_imports_classes.add("org.apache.commons.lang.StringEscapeUtils");
    _jspx_imports_classes.add("java.io.InputStream");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
        //this is to catch someone that bookmarked a page after selecting a language
        Cookie[] cookies2 = request.getCookies();
        if (cookies2 != null && cookies2.length > 0) {
                for (int i = 0; i < cookies2.length; i++) {
                        if (cookies2[i] != null && cookies2[i].getName() != null && cookies2[i].getName().equalsIgnoreCase("locale")) {
                                if (cookies2[i].getValue() != null) {
                                        session.setAttribute("locale", cookies2[i].getValue());
                                }
                        }
                }
        }
        if (session.getAttribute("locale") == null) {
                //last chance, default to english
                session.setAttribute("locale", "en");
        }

      out.write("<html lang=\"");
      out.print((String) session.getAttribute("locale"));
      out.write("\" dir=\"");
      out.print(ResourceLoader.GetResource(session, "direction"));
      out.write("\">\r\n");
      out.write("        <head>\r\n");
      out.write("                <meta charset=\"utf-8\">\r\n");
      out.write("                <title>");
      out.print(ResourceLoader.GetResource(session, "title"));
      out.write("</title>\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <meta name=\"description\" content=\"");
      out.print(ResourceLoader.GetResource(session, "description"));
      out.write("\">\r\n");
      out.write("                <meta name=\"author\" content=\"Apache Software Foundation\">\r\n");
      out.write("\r\n");
      out.write("                <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("                <link href=\"css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\">\r\n");
      out.write("                <link href=\"css/bootstrap-timepicker.min.css\" rel=\"stylesheet\">\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"css/ui-lightness/jquery-ui-1.10.2.custom.min.css\">\r\n");
      out.write("                <!--[if IE 7]>\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"css/font-awesome-ie7.min.css\">\r\n");
      out.write("                <![endif]-->\r\n");
      out.write("\r\n");
      out.write("                <link rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("                <style type=\"text/css\">\r\n");
      out.write("                        body {\r\n");
      out.write("                                padding-top: 60px;\r\n");
      out.write("                                padding-bottom: 40px;\r\n");
      out.write("                        }\r\n");
      out.write("                        .tab-content {\r\n");
      out.write("                                overflow: visible;\r\n");
      out.write("                            }\r\n");
      out.write("                </style>\r\n");
      out.write("                <link href=\"css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("                <link href=\"css/bootstrap-modal.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("                <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n");
      out.write("                <!--[if lt IE 9]>\r\n");
      out.write("                  <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("                <![endif]-->\r\n");
      out.write("\r\n");
      out.write("                <!-- Fav and touch icons -->\r\n");
      out.write("\r\n");
      out.write("                <link rel=\"shortcut icon\" href=\"ico/favicon.png\">\r\n");
      out.write("                <script src=\"js/jquery-1.9.1.js\"></script>\r\n");
      out.write("                <script src=\"js/i18n.js.jsp\"></script>\r\n");
      out.write("                <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("                <script src=\"js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("                <script src=\"js/bootstrap-timepicker.min.js\"></script>\r\n");
      out.write("                <script src=\"js/bootstrap-modalmanager.js\"></script>\r\n");
      out.write("                <script src=\"js/bootstrap-modal.js\"></script>\r\n");
      out.write("                <script src=\"js/jquery.jeditable.js\"></script>\r\n");
      out.write("                <script src=\"js/jquery-ui-1.10.2.custom.min.js\"></script>\r\n");
      out.write("                <script src=\"js/main.js\"></script>\r\n");
      out.write("        </head>\r\n");
      out.write("\r\n");
      out.write("        <body>\r\n");
      out.write("                ");

    UddiHub internal_ = UddiHub.getInstance(application, session);
    if (internal_.isAutoLogoutEnabled()) {


      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    var timer1, timer2;\r\n");
      out.write("    document.onkeypress = resetTimer;\r\n");
      out.write("    document.onmousemove = resetTimer;\r\n");
      out.write("    function resetTimer()\r\n");
      out.write("    {\r\n");
      out.write("\r\n");
      out.write("        $(\"#autologout\").modal('hide');\r\n");
      out.write("        clearTimeout(timer1);\r\n");
      out.write("        clearTimeout(timer2);\r\n");
      out.write("\r\n");
      out.write("        // waiting time in minutes\r\n");
      out.write("        var wait = ");
      out.print(internal_.GetAutoLogoutDuration());
      out.write(";\r\n");
      out.write("\r\n");
      out.write("        // alert user one minute before\r\n");
      out.write("        timer1 = setTimeout(\"alertUser()\", (wait) - 30000);\r\n");
      out.write("\r\n");
      out.write("        // logout user\r\n");
      out.write("        timer2 = setTimeout(\"logout()\", wait);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function alertUser()\r\n");
      out.write("    {\r\n");
      out.write("        window.console && console.log(\"trigger automatic logout warning\");\r\n");
      out.write("        $(\"#autologout\").modal('hide');\r\n");
      out.write("        $(\"#autologout\").modal('show');\r\n");
      out.write("        // document.getElementById('timeoutPopup').style.display = 'block';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function logout()\r\n");
      out.write("    {\r\n");
      out.write("        window.console && console.log(\"trigger automatic logout\");\r\n");
      out.write("        window.location.href = 'logoutredir.jsp';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal hide fade container\" id=\"autologout\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("        <h3>");
      out.print(ResourceLoader.GetResource(session, "pages.serviceimport.content.sslwarning"));
      out.write("</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("        ");
      out.print(ResourceLoader.GetResource(session, "pages.session.expire"));
      out.write("</div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("\r\n");
      out.write("        <a href=\"javascript:closeXmlPop('autologout');\" class=\"btn\">");
      out.print(ResourceLoader.GetResource(session, "modal.close"));
      out.write("</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

    }


      out.write("<form id=\"uddiform\">\r\n");
      out.write("                        ");

    //this is to catch someone that bookmarked a page after selecting a language
    Cookie[] cookies3 = request.getCookies();
    if (cookies3 != null && cookies3.length > 0) {
        for (int i = 0; i < cookies3.length; i++) {
            if (cookies3[i] != null && cookies3[i].getName() != null && cookies3[i].getName().equalsIgnoreCase("locale")) {
                if (cookies3[i].getValue() != null) {
                    session.setAttribute("locale", cookies3[i].getValue());
                }
            }
        }
    }
    if (session.getAttribute("locale")==null){
        //last change, default to english
        session.setAttribute("locale", "en");
    }
    String currentNonce = null;

    if (request.getMethod().equalsIgnoreCase("post")) {

        if ((request.getParameter("nonce") == null || request.getParameter("nonce").isEmpty())) {
            //reject it
            session.removeAttribute("nonce");
            response.sendRedirect("index.jsp");
            UddiHub.log.warn( "CSRF Test failed, no nonce guid." + request.getRemoteAddr() + request.getRemoteUser());
            //throw new CrossSiteRequestForgeryException();
             response.sendRedirect("index.jsp");
                
                return;
        } else {

            String noncestr = (String) session.getAttribute("nonce");
            if (noncestr == null) {
                //no session variable to test against, reject it
                UddiHub.log.warn( "CSRF Test failed, no session guid." + request.getRemoteAddr() + request.getRemoteUser());
                session.removeAttribute("nonce");
                response.sendRedirect("index.jsp");
                
                return;
                //throw new CrossSiteRequestForgeryException("Cross Site Request Forgery");
            }
            String postedstr = request.getParameter("nonce");

            //check session against existing nonce, if match
            //generate new one, add to page and session
            //else redirect to index page
            if (noncestr.equals(postedstr)) {
                currentNonce = noncestr;
                //OK
                // current = UUID.randomUUID();
                //session.removeAttribute("nonce");
                // session.setAttribute("nonce", current.toString());
                UddiHub.log.debug("CSRF Test passed.");
            } else {
                //mismatch, reject it
                UddiHub.log.warn( "CSRF Test failed, session did not match nonce guid." + request.getRemoteAddr() + request.getRemoteUser());
                session.removeAttribute("nonce");
                response.sendRedirect("index.jsp");
                return;
                //throw new CrossSiteRequestForgeryException("Cross Site Request Forgery");
            }
        }
    } else {
        //HTTP GET or otherwise message
        if ((currentNonce == null) || currentNonce.isEmpty()) {
            currentNonce = (String)session.getAttribute("nonce");
            if (currentNonce == null) {
                currentNonce = java.util.UUID.randomUUID().toString();
            }
            session.setAttribute("nonce", currentNonce);
        }

    }


      out.write("<input type=\"hidden\" name=\"nonce\" id=\"nonce\" value=\"");
      out.print(StringEscapeUtils.escapeHtml((String) session.getAttribute("nonce")));
      out.write("\" />\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"modal hide fade container\" id=\"alert\">\r\n");
      out.write("                                <div class=\"modal-header\">\r\n");
      out.write("                                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("                                        <h3>");
      out.print(ResourceLoader.GetResource(session, "actions.result"));
      out.write("</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                        <div id=\"alert_results\"><i class=\"icon-2x icon-thumbs-up\"></i></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"modal-footer\">\r\n");
      out.write("\r\n");
      out.write("                                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">");
      out.print(ResourceLoader.GetResource(session, "modal.close"));
      out.write("</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("    \r\n");
      out.write("                        ");

                                UddiHub hub = UddiHub.getInstance(application, session);
                                Cookie[] cs = request.getCookies();
                                String newnode=null;
                                if (cs!=null){
                                        for (int i=0; i < cs.length; i++){
                                                if (cs[i].getName().equalsIgnoreCase("current_node")){
                                                        newnode = cs[i].getValue();
                                                        break;
                                                }
                                        }
                                }
                                hub.switchNodes(newnode);
                        
      out.write("<div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("                                <div class=\"navbar-inner\">\r\n");
      out.write("                                        <div class=\"container\">\r\n");
      out.write("                                                <button type=\"button\" class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\r\n");
      out.write("                                                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                                                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                                                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                                                </button>\r\n");
      out.write("                                                <a class=\"brand\" href=\"home.jsp\" style=\"padding-left:19px; padding-top:0px; padding-bottom:0px\"><img src=\"img/logo2.png\"></a>\r\n");
      out.write("                                                <div class=\"nav-collapse collapse\">\r\n");
      out.write("                                                        <ul class=\"nav\">\r\n");
      out.write("                                                                <li class=\"dropdown\"><a href=\"home.jsp\" data-toggle=\"dropdown\" class=\"dropdowb-town\"><i class=\"icon-home icon-large\"></i>");
      out.print(ResourceLoader.GetResource(session, "navbar.home"));
      out.write("<b class=\"caret\"></b></a>\r\n");
      out.write("                                                                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                                                <li><a href=\"reginfo.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.create.mybiz.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.create.mybiz"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"assertions.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.publisherassertions.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.publisherassertions"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"transfer.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.transfer.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.transfer"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li class=\"divider\"></li>\r\n");
      out.write("                                                                                <li><a href=\"viewSubscriptions.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.subscriptions.view.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.subscriptions.view"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"editSubscription.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.subscriptions.create.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.subscriptions.create"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"subscriptionFeed.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.subscriptions.feed.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.subscriptions.feed"));
      out.write("</a></li>\r\n");
      out.write("                                                                        </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li class=\"dropdown\" ><a href=\"#\" data-toggle=\"dropdown\" class=\"dropdowb-town\"><i class=\"icon-search icon-large\"></i>");
      out.print(ResourceLoader.GetResource(session, "navbar.discover"));
      out.write("<b class=\"caret\"></b></a>\r\n");
      out.write("                                                                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                                                <li><a href=\"businessBrowse.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.businesses.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.businesses"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"serviceBrowse.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.services.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.services"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"tmodelBrowse.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.tmodels.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.tmodels"));
      out.write("</a></li>\r\n");
      out.write("                                                                                        ");
//                                        <li><a href="publisherBrowse.jsp" title="<%=ResourceLoader.GetResource(session, "navbar.publishers.tooltip")">ResourceLoader.GetResource(session, "navbar.publishers")</a></li>
                                                                                               
      out.write("<li class=\"divider\"> </li>\r\n");
      out.write("\r\n");
      out.write("                                                                                <li><a href=\"search.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.search.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.search"));
      out.write("</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                                        </ul>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <li class=\"dropdown\"><a href=\"#\" data-toggle=\"dropdown\" class=\"dropdowb-town\"><i class=\"icon-pencil icon-large\"></i>");
      out.print(ResourceLoader.GetResource(session, "navbar.create"));
      out.write("<b class=\"caret\"></b></a>\r\n");
      out.write("                                                                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                                                <li><a href=\"businessEditor2.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.create.business.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.create.business"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"businessBrowse.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.create.service.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.create.service"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"importFromWsdl.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.create.serviceimport.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.create.serviceimport"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"importFromWadl.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.create.serviceimport.tooltip.wadl"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.create.serviceimport.wadl"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"tmodelEditor.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.create.tmodel.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.create.tmodel"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"tmodelPartitions.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.create.tmodelkeygen.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.create.tmodelkeygen"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"editSubscription.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.subscriptions.create.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.subscriptions"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"advanced.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.advanced"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.advanced"));
      out.write("</a></li>\r\n");
      out.write("                                                                        </ul>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("\r\n");
      out.write("                                                                <li class=\"dropdown\"><a href=\"#\" data-toggle=\"dropdown\" class=\"dropdowb-town\"><i class=\"icon-cog icon-large\"></i>");
      out.print(ResourceLoader.GetResource(session, "navbar.settings"));
      out.write("<b class=\"caret\"></b></a>\r\n");
      out.write("                                                                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                                                <li><a href=\"settings.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.settings.config.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.settings.config"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li class=\"divider\"></li>\r\n");
      out.write("                                                                                <li><a href=\"#\" data-toggle=\"tooltip\" data-container=\"body\" class=\"uddi_tooltips\" title=\"");
      out.print(ResourceLoader.GetResource(session, "items.switchnode.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "items.switchnode"));
      out.write("</a></li>\r\n");
      out.write("                                                                                \r\n");
      out.write("                                                                                        ");

                                                                                                List<Node> nodes = hub.GetJuddiClientConfig().getUDDINodeList();
                                                                                                for (int i = 0; i < nodes.size(); i++) {
                                                                                                        out.write("<li><a href=\"javascript:switchNode('" + StringEscapeUtils.escapeHtml(nodes.get(i).getName()) + "')\" title=\"" + StringEscapeUtils.escapeHtml(nodes.get(i).getDescription()) + "\" >");
                                                                                                        if (hub.getNodeName().equals(nodes.get(i).getName())) {
                                                                                                                out.write("<i class=\"icon icon-check\"></i> ");
                                                                                                        } else {
                                                                                                                out.write("<i class=\"icon icon-check-empty\"></i> ");
                                                                                                        }
                                                                                                        out.write(StringEscapeUtils.escapeHtml(nodes.get(i).getName()));
                                                                                                        if (hub.getNodeName().equals(nodes.get(i).getName())) {
                                                                                                                out.write("(" + ResourceLoader.GetResource(session, "items.active") + ")");
                                                                                                        }
                                                                                                        out.write("</a></li>");
                                                                                                }
                                                                                        
      out.write("</ul>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                                <script type=\"text/javascript\">\r\n");
      out.write("                                                                         $('.uddi_tooltips').tooltip();\r\n");
      out.write("                                                                        function switchNode(name) {\r\n");
      out.write("                                                                                var postbackdata = new Array();\r\n");
      out.write("                                                                                postbackdata.push({\r\n");
      out.write("                                                                                        name: \"nonce\",\r\n");
      out.write("                                                                                        value: $(\"#nonce\").val()\r\n");
      out.write("                                                                                });\r\n");
      out.write("                                                                                postbackdata.push({\r\n");
      out.write("                                                                                        name: \"node\",\r\n");
      out.write("                                                                                        value: name\r\n");
      out.write("                                                                                });\r\n");
      out.write("                                                                                window.console && console.log('reconfiguring node name');\r\n");
      out.write("                                                                                var request = $.ajax({\r\n");
      out.write("                                                                                        url: 'ajax/switch.jsp',\r\n");
      out.write("                                                                                        type: \"POST\",\r\n");
      out.write("                                                                                        cache: false,\r\n");
      out.write("                                                                                        data: postbackdata\r\n");
      out.write("                                                                                });\r\n");
      out.write("\r\n");
      out.write("                                                                                request.done(function(msg) {\r\n");
      out.write("                                                                                        window.console && console.log(msg);\r\n");
      out.write("                                                                                        window.console && console.log('postback done to div ' );\r\n");
      out.write("                                                                                        $(\"#\" + jqSelector('nodeswitcherdetails')).html(msg);\r\n");
      out.write("                                                                                        $(\"#nodeswitcher\").modal();\r\n");
      out.write("                                                                                });\r\n");
      out.write("\r\n");
      out.write("                                                                                request.fail(function(jqXHR, textStatus) {\r\n");
      out.write("                                                                                        window.console && console.log('postback failed ');\r\n");
      out.write("                                                                                        $(\"#\" + jqSelector('nodeswitcherdetails')).html(\"An error occured! \" + jqXHR.responseText + textStatus);\r\n");
      out.write("                                                                                        $(\"#nodeswitcher\").modal();\r\n");
      out.write("                                                                                });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                                        }\r\n");
      out.write("                                                                </script>\r\n");
      out.write("\r\n");
      out.write("                                                                <li class=\"dropdown\"><a href=\"#\" data-toggle=\"dropdown\" class=\"dropdowb-town\"><i class=\"icon-question-sign icon-large\"></i>");
      out.print(ResourceLoader.GetResource(session, "navbar.help"));
      out.write("<b class=\"caret\"></b></a>\r\n");
      out.write("                                                                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                                                <li><a href=\"http://juddi.apache.org/docs.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.userguide"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.userguide"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"http://wiki.apache.org/juddi\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.wiki"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.wiki"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"http://juddi.apache.org/issue-tracking.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.bugreport"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.bugreport"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"http://juddi.apache.org/\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.website"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.website"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"http://juddi.apache.org/mailing-list.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.mailinglist"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.mailinglist"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"http://juddi.apache.org/source.html\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.source"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.source"));
      out.write("</a></li>\r\n");
      out.write("                                                                                <li><a href=\"about.jsp\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.help.about.tooltip"));
      out.write('"');
      out.write('>');
      out.print(ResourceLoader.GetResource(session, "navbar.help.about"));
      out.write("</a></li>\r\n");
      out.write("\r\n");
      out.write("                                                                        </ul>\r\n");
      out.write("                                                                </li>\r\n");
      out.write("                                                        </ul>\r\n");
      out.write("                                                        <div id=\"loginfield\">\r\n");
      out.write("                                                                ");
      out.write("<div class=\"navbar-form pull-right\">\r\n");
      out.write("\r\n");
      out.write("    ");

        if (session.getAttribute("username") != null && session.getAttribute("password") != null
                && ((String) session.getAttribute("username")).length() > 0 && ((String) session.getAttribute("password")).length() > 0) {
            //we're probably logged in

    
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        loggedin = true;\r\n");
      out.write("    </script>\r\n");
      out.write("    <a class=\"btn\" title=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.login.logout"));
      out.write("\" href=\"javascript:logout();\">\r\n");
      out.write("        ");

                if (!request.isSecure() ||  !UddiHub.getInstance(application, session).isSecure()) {
            
      out.write("<i class=\"icon-warning-sign\" title=\"");
      out.print(ResourceLoader.GetResource(session, "warning.ssl"));
      out.write("\"></i>\r\n");
      out.write("            ");

                }
            
      out.write("<i class=\"icon-user\"></i>\r\n");
      out.write("        ");

            out.write(ResourceLoader.GetResource(session, "items.welcome") + " " + StringEscapeUtils.escapeHtml((String) session.getAttribute("username")) + "</a>");

        } else {
        
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("            loggedin = false;\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <input class=\"span2\" type=\"text\" placeholder=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.login.username"));
      out.write("\" name=\"username\" id=\"username\">\r\n");
      out.write("        <input class=\"span2\" type=\"password\" placeholder=\"");
      out.print(ResourceLoader.GetResource(session, "navbar.login.password"));
      out.write("\" name=\"password\" id=\"password\">\r\n");
      out.write("        <button type=\"button\" onclick=\"javascript:Login();\" class=\"btn\" id=\"loginbutton\">\r\n");
      out.write("            ");

                if (!request.isSecure()) {
            
      out.write("<i class=\"icon-warning-sign\" title=\"");
      out.print(ResourceLoader.GetResource(session, "warning.ssl"));
      out.write("\"></i>\r\n");
      out.write("            ");

                }
            
      out.print(ResourceLoader.GetResource(session, "navbar.login.button"));
      out.write("</button>\r\n");
      out.write("        ");

            }
        
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("<div class=\"modal hide fade container\" id=\"loginfailure\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("        <h3>");
      out.print(ResourceLoader.GetResource(session, "errors.generic"));
      out.write("</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("            <i class=\"icon-4x icon-thumbs-down\"></i><br>\r\n");
      out.write("            <div id=\"loginfailuredetails\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("\r\n");
      out.write("        <button type=\"button\" class=\"btn\" data-dismiss=\"modal\" >");
      out.print(ResourceLoader.GetResource(session, "modal.close"));
      out.write("</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("</div>\r\n");
      out.write("                                                </div><!--/.nav-collapse -->\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                        \r\n");
      out.write("                                                        \r\n");
      out.write("<div class=\"modal hide fade container\" id=\"nodeswitcher\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("        <h3>");
      out.print(ResourceLoader.GetResource(session, "items.switchnode"));
      out.write("</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("            <div id=\"nodeswitcherdetails\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"index.jsp\" class=\"btn btn-primary\" >");
      out.print(ResourceLoader.GetResource(session, "actions.continue"));
      out.write("</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("     <!-- Main hero unit for a primary marketing message or call to action -->\r\n");
      out.write("     <div class=\"well\" >\r\n");
      out.write("          <h1>");
      out.print( ResourceLoader.GetResource(session, "navbar.search"));
      out.write("</h1>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("     <!-- Example row of columns -->\r\n");
      out.write("     <div class=\"row\">\r\n");
      out.write("          <div class=\"span12\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               ");

                    UddiHub x = UddiHub.getInstance(application, request.getSession());

               
      out.write("<div class=\"accordion\" id=\"accordion2\">\r\n");
      out.write("                    <div class=\"accordion-group\">\r\n");
      out.write("                         <div class=\"accordion-heading\">\r\n");
      out.write("                              <a class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#accordion2\" href=\"#collapseOne\">\r\n");
      out.write("                                   <b>");
      out.print( ResourceLoader.GetResource(session, "navbar.search"));
      out.write(" !</b>\r\n");
      out.write("                              </a>\r\n");
      out.write("                         </div>\r\n");
      out.write("                         <div id=\"collapseOne\" class=\"accordion-body collapse in\">\r\n");
      out.write("                              <div class=\"accordion-inner\">\r\n");
      out.write("                                   ");
      out.print( ResourceLoader.GetResource(session, "search.wrylf"));
      out.write("<Br>\r\n");
      out.write("                                   <div class=\"btn-group\" id=\"searchfor\" data-toggle=\"buttons-radio\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn active\" value=\"business\">");
      out.print( ResourceLoader.GetResource(session, "items.business"));
      out.write("</button>\r\n");
      out.write("                                        <!--<button type=\"button\" class=\"btn \" >Related Business</button>-->\r\n");
      out.write("                                        <button type=\"button\" class=\"btn \" value=\"service\">");
      out.print( ResourceLoader.GetResource(session, "items.service"));
      out.write("</button>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn \" value=\"bindingTemplate\">");
      out.print( ResourceLoader.GetResource(session, "items.bindingtemplate"));
      out.write("</button>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn \" value=\"tModel\">");
      out.print( ResourceLoader.GetResource(session, "items.tmodel"));
      out.write("</button>\r\n");
      out.write("                                   </div><br><Br>\r\n");
      out.write("                                   ");
      out.print( ResourceLoader.GetResource(session, "search.criteria"));
      out.write("<br>\r\n");
      out.write("                                   <div class=\"btn-group\" id=\"searchcriteria\" data-toggle=\"buttons-radio\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn active\" value=\"name\">");
      out.print( ResourceLoader.GetResource(session, "search.criteria.byname"));
      out.write("</button>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn \" value=\"category\">");
      out.print( ResourceLoader.GetResource(session, "search.criteria.bycategory"));
      out.write("</button>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn \" value=\"key\">");
      out.print( ResourceLoader.GetResource(session, "search.criteria.bykey"));
      out.write("</button>\r\n");
      out.write("                                        <button type=\"button\" class=\"btn \" value=\"tmodel\">");
      out.print( ResourceLoader.GetResource(session, "search.criteria.bytmodel"));
      out.write("</button>\r\n");
      out.write("                                   </div><br>\r\n");
      out.write("                                   ");
      out.print(ResourceLoader.GetResource(session, "items.findqualifiers"));
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("                                   <div style=\" float:left; padding: 2px\">\r\n");
      out.write("\r\n");
      out.write("                                        <div ><div  class=\"hide warning\" id=\"");
      out.print(UDDIConstants.AND_ALL_KEYS);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" id=\"");
      out.print(UDDIConstants.AND_ALL_KEYS);
      out.write("\" name=\"");
      out.print(UDDIConstants.AND_ALL_KEYS);
      out.write("\" value=\"");
      out.print(UDDIConstants.AND_ALL_KEYS);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.AND_ALL_KEYS)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.AND_ALL_KEYS);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div  class=\"hide warning\" id=\"");
      out.print(UDDIConstants.APPROXIMATE_MATCH);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" id=\"");
      out.print(UDDIConstants.APPROXIMATE_MATCH);
      out.write("\" name=\"");
      out.print(UDDIConstants.APPROXIMATE_MATCH);
      out.write("\" value=\"");
      out.print(UDDIConstants.APPROXIMATE_MATCH);
      out.write("\" checked=\"checked\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.APPROXIMATE_MATCH)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.APPROXIMATE_MATCH);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div  class=\"hide warning\" id=\"");
      out.print(UDDIConstants.BINARY_SORT);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" id=\"");
      out.print(UDDIConstants.BINARY_SORT);
      out.write("\" name=\"");
      out.print(UDDIConstants.BINARY_SORT);
      out.write("\" value=\"");
      out.print(UDDIConstants.BINARY_SORT);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.BINARY_SORT)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.BINARY_SORT);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div  class=\"hide warning\" id=\"");
      out.print(UDDIConstants.BINDING_SUBSET);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" id=\"");
      out.print(UDDIConstants.BINDING_SUBSET);
      out.write("\" name=\"");
      out.print(UDDIConstants.BINDING_SUBSET);
      out.write("\" value=\"");
      out.print(UDDIConstants.BINDING_SUBSET);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.BINDING_SUBSET)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.BINDING_SUBSET);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div  class=\"hide warning\" id=\"");
      out.print(UDDIConstants.CASE_INSENSITIVE_MATCH);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" id=\"");
      out.print(UDDIConstants.CASE_INSENSITIVE_MATCH);
      out.write("\" name=\"");
      out.print(UDDIConstants.CASE_INSENSITIVE_MATCH);
      out.write("\" value=\"");
      out.print(UDDIConstants.CASE_INSENSITIVE_MATCH);
      out.write("\"  checked=\"checked\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.CASE_INSENSITIVE_MATCH)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.CASE_INSENSITIVE_MATCH);
      out.write("</a></div>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   <div style=\" float:left; padding: 2px\">\r\n");
      out.write("                                        <div ><div class=\"hide warning\" id=\"");
      out.print(UDDIConstants.CASE_INSENSITIVE_SORT);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.CASE_INSENSITIVE_SORT);
      out.write("\" value=\"");
      out.print(UDDIConstants.CASE_INSENSITIVE_SORT);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.CASE_INSENSITIVE_SORT)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.CASE_INSENSITIVE_SORT);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.CASE_SENSITIVE_MATCH);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.CASE_SENSITIVE_MATCH);
      out.write("\" value=\"");
      out.print(UDDIConstants.CASE_SENSITIVE_MATCH);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.CASE_SENSITIVE_MATCH)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.CASE_SENSITIVE_MATCH);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.CASE_SENSITIVE_SORT);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.CASE_SENSITIVE_SORT);
      out.write("\" value=\"");
      out.print(UDDIConstants.CASE_SENSITIVE_SORT);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.CASE_SENSITIVE_SORT)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.CASE_SENSITIVE_SORT);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.COMBINE_CATEGORY_BAGS);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.COMBINE_CATEGORY_BAGS);
      out.write("\" value=\"");
      out.print(UDDIConstants.COMBINE_CATEGORY_BAGS);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.COMBINE_CATEGORY_BAGS)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.COMBINE_CATEGORY_BAGS);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.DIACRITIC_INSENSITIVE_MATCH);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.DIACRITIC_INSENSITIVE_MATCH);
      out.write("\" value=\"");
      out.print(UDDIConstants.DIACRITIC_INSENSITIVE_MATCH);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.DIACRITIC_INSENSITIVE_MATCH)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.DIACRITIC_INSENSITIVE_MATCH);
      out.write("</a></div>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   <div style=\" float:left; padding: 2px\">\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.DIACRITIC_SENSITIVE_MATCH);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.DIACRITIC_SENSITIVE_MATCH);
      out.write("\" value=\"");
      out.print(UDDIConstants.DIACRITIC_SENSITIVE_MATCH);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.DIACRITIC_SENSITIVE_MATCH)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.DIACRITIC_SENSITIVE_MATCH);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.EXACT_MATCH);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.EXACT_MATCH);
      out.write("\" value=\"");
      out.print(UDDIConstants.EXACT_MATCH);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.EXACT_MATCH)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.EXACT_MATCH);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.OR_ALL_KEYS);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.OR_ALL_KEYS);
      out.write("\" value=\"");
      out.print(UDDIConstants.OR_ALL_KEYS);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.OR_ALL_KEYS)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.OR_ALL_KEYS);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.OR_LIKE_KEYS);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.OR_LIKE_KEYS);
      out.write("\" value=\"");
      out.print(UDDIConstants.OR_LIKE_KEYS);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.OR_LIKE_KEYS)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.OR_LIKE_KEYS);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.SERVICE_SUBSET);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.SERVICE_SUBSET);
      out.write("\" value=\"");
      out.print(UDDIConstants.SERVICE_SUBSET);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.SERVICE_SUBSET)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.SERVICE_SUBSET);
      out.write("</a></div>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   <div style=\" float:left; padding: 2px\">\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.SIGNATURE_PRESENT);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.SIGNATURE_PRESENT);
      out.write("\" value=\"");
      out.print(UDDIConstants.SIGNATURE_PRESENT);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.SIGNATURE_PRESENT)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.SIGNATURE_PRESENT);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.SORT_BY_DATE_ASC);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.SORT_BY_DATE_ASC);
      out.write("\" value=\"");
      out.print(UDDIConstants.SORT_BY_DATE_ASC);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.SORT_BY_DATE_ASC)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.SORT_BY_DATE_ASC);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.SORT_BY_DATE_DESC);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.SORT_BY_DATE_DESC);
      out.write("\" value=\"");
      out.print(UDDIConstants.SORT_BY_DATE_DESC);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.SORT_BY_DATE_DESC)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.SORT_BY_DATE_DESC);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.SORT_BY_NAME_ASC);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.SORT_BY_NAME_ASC);
      out.write("\" value=\"");
      out.print(UDDIConstants.SORT_BY_NAME_ASC);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.SORT_BY_NAME_ASC)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.SORT_BY_NAME_ASC);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div class=\"hide warning\"  id=\"");
      out.print(UDDIConstants.SORT_BY_NAME_DESC);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.SORT_BY_NAME_DESC);
      out.write("\" value=\"");
      out.print(UDDIConstants.SORT_BY_NAME_DESC);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.SORT_BY_NAME_DESC)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.SORT_BY_NAME_DESC);
      out.write("</a></div>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   <div style=\" float:left; padding: 2px\">\r\n");
      out.write("                                        <div ><div  class=\"hide warning\" id=\"");
      out.print(UDDIConstants.SUPPRESS_PROJECTED_SERVICES);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.SUPPRESS_PROJECTED_SERVICES);
      out.write("\" value=\"");
      out.print(UDDIConstants.SUPPRESS_PROJECTED_SERVICES);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.SUPPRESS_PROJECTED_SERVICES)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.SUPPRESS_PROJECTED_SERVICES);
      out.write("</a></div>\r\n");
      out.write("                                        <div ><div  class=\"hide warning\" id=\"");
      out.print(UDDIConstants.UTS_10);
      out.write("w\"><i class=\"icon-warning-sign\"></i></div><input type=\"checkbox\" name=\"");
      out.print(UDDIConstants.UTS_10);
      out.write("\" value=\"");
      out.print(UDDIConstants.UTS_10);
      out.write("\"> <a href=\"#\" data-toggle=\"tooltip\" title=\"\" data-original-title=\"");
      out.print(StringEscapeUtils.escapeHtml(ResourceLoader.GetResource(session, UDDIConstants.UTS_10)));
      out.write("\" class=\"mytooltip\" data-container=\"body\">");
      out.print(UDDIConstants.UTS_10);
      out.write("</a></div>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   <Br>\r\n");
      out.write("                                   <br><br><br>\r\n");
      out.write("                                   <div>\r\n");
      out.write("                                        <br><Br>\r\n");
      out.write("                                        <input type=\"text\" placeholder=\"Type something…\" id=\"searchcontent\">\r\n");
      out.write("                                        <input type=\"text\" placeholder=\"Language\" id=\"lang\"><br>\r\n");
      out.write("                                        ");
      out.print( ResourceLoader.GetResource(session, "search.tip"));
      out.write("<br>\r\n");
      out.write("                                        <a href=\"javascript:search();\" class=\"btn btn-primary btn-large\">");
      out.print( ResourceLoader.GetResource(session, "navbar.search"));
      out.write("</a>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"accordion-group\">\r\n");
      out.write("                         <div class=\"accordion-heading\">\r\n");
      out.write("                              <a class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#accordion2\" href=\"#collapseTwo\">\r\n");
      out.write("                                   ");
      out.print( ResourceLoader.GetResource(session, "search.results"));
      out.write("</a>\r\n");
      out.write("                         </div>\r\n");
      out.write("                         <div id=\"collapseTwo\" class=\"accordion-body collapse\">\r\n");
      out.write("                              <div class=\"accordion-inner\" id=\"resultdivs\">\r\n");
      out.write("                                   ");
      out.print( ResourceLoader.GetResource(session, "search.searchfirst"));
      out.write("</div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("          $(document).ready(function() {\r\n");
      out.write("               $(':checkbox').click(function() {\r\n");
      out.write("                    checkForIllegalCombos();\r\n");
      out.write("                    return true;\r\n");
      out.write("               });\r\n");
      out.write("               $('.mytooltip').tooltip();\r\n");
      out.write("          });\r\n");
      out.write("\r\n");
      out.write("          function checkForIllegalCombos() {\r\n");
      out.write("               var selected = new Array();\r\n");
      out.write("               $('.warning').hide();\r\n");
      out.write("\r\n");
      out.write("               $(':checkbox').each(function(key, value) {\r\n");
      out.write("                    if (value.checked)\r\n");
      out.write("                    {\r\n");
      out.write("                         //alert(value.value);\r\n");
      out.write("                         selected.push(value.value);\r\n");
      out.write("                    }\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("               var andAllKeys = indexOf.call(selected, \"andAllKeys\");\r\n");
      out.write("               var orAllKeys = indexOf.call(selected, \"orAllKeys\");\r\n");
      out.write("               var orLikeKeys = indexOf.call(selected, \"orLikeKeys\");\r\n");
      out.write("\r\n");
      out.write("               var sortByNameAsc = indexOf.call(selected, \"sortByNameAsc\");\r\n");
      out.write("               var sortByNameDesc = indexOf.call(selected, \"sortByNameDesc\");\r\n");
      out.write("\r\n");
      out.write("               var sortByDateAsc = indexOf.call(selected, \"sortByDateAsc\");\r\n");
      out.write("               var sortByDateDesc = indexOf.call(selected, \"sortByDateDesc\");\r\n");
      out.write("\r\n");
      out.write("               var combineCategoryBags = indexOf.call(selected, \"combineCategoryBags\");\r\n");
      out.write("               var serviceSubset = indexOf.call(selected, \"serviceSubset\");\r\n");
      out.write("               var bindingSubset = indexOf.call(selected, \"bindingSubset\");\r\n");
      out.write("\r\n");
      out.write("               var exactMatch = indexOf.call(selected, \"exactMatch\");\r\n");
      out.write("               var approximateMatch = indexOf.call(selected, \"approximateMatch\");\r\n");
      out.write("\r\n");
      out.write("               //and exact\r\n");
      out.write("               var caseInsensitiveMatch = indexOf.call(selected, \"caseInsensitiveMatch\");\r\n");
      out.write("\r\n");
      out.write("               var binarySort = indexOf.call(selected, \"binarySort\");\r\n");
      out.write("               var uts10 = indexOf.call(selected, \"UTS-10\");\r\n");
      out.write("\r\n");
      out.write("               var diacriticSensitiveMatch = indexOf.call(selected, \"diacriticSensitiveMatch\");\r\n");
      out.write("               var diacriticInsensitiveMatch = indexOf.call(selected, \"diacriticInsensitiveMatch\");\r\n");
      out.write("\r\n");
      out.write("               //exactMatch and diacriticInsensitiveMatch are mutually exclusive\r\n");
      out.write("               \r\n");
      out.write("               //  caseSensitiveSort and caseInsensitiveSort are mutually exclusive\r\n");
      out.write("               var caseSensitiveSort = indexOf.call(selected, \"caseSensitiveSort\");\r\n");
      out.write("               var caseInsensitiveSort = indexOf.call(selected, \"caseInsensitiveSort\");\r\n");
      out.write("\r\n");
      out.write("               //caseSensitiveMatch and caseInsensitiveMatch are mutually exclusive\r\n");
      out.write("               var caseSensitiveMatch = indexOf.call(selected, \"caseSensitiveMatch\");\r\n");
      out.write("               \r\n");
      out.write("               if ((andAllKeys >= 0 && (orAllKeys >=0 || orLikeKeys  >=0)) ||\r\n");
      out.write("                       ((andAllKeys >= 0 || orAllKeys >=0) && orLikeKeys  >=0) || \r\n");
      out.write("                       ((andAllKeys >= 0 ||  orLikeKeys >=0) && orAllKeys  >=0) )\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#andAllKeysw\").show();\r\n");
      out.write("                    $(\"#orAllKeysw\").show();\r\n");
      out.write("                    $(\"#orLikeKeysw\").show();\r\n");
      out.write("               }\r\n");
      out.write("               if (sortByNameDesc >= 0 && sortByNameAsc >=0)\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#sortByNameAscw\").show();\r\n");
      out.write("                    $(\"#sortByNameDescw\").show();\r\n");
      out.write("               }\r\n");
      out.write("               if (sortByDateAsc >= 0 && sortByDateDesc >=0)\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#sortByDateAscw\").show();\r\n");
      out.write("                    $(\"#sortByDateDescw\").show();\r\n");
      out.write("               }\r\n");
      out.write("               if (exactMatch >= 0 && approximateMatch >=0)\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#exactMatchw\").show();\r\n");
      out.write("                    $(\"#approximateMatchw\").show();\r\n");
      out.write("               }\r\n");
      out.write("               if (exactMatch >= 0 && caseInsensitiveMatch >=0)\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#exactMatchw\").show();\r\n");
      out.write("                    $(\"#caseInsensitiveMatchw\").show();\r\n");
      out.write("               }\r\n");
      out.write("               \r\n");
      out.write("               if (binarySort >= 0 && uts10 >=0)\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#binarySortw\").show();\r\n");
      out.write("                    $(\"#UTS-10w\").show();\r\n");
      out.write("               }\r\n");
      out.write("               if (diacriticSensitiveMatch >= 0 && diacriticInsensitiveMatch >=0)\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#diacriticSensitiveMatchw\").show();\r\n");
      out.write("                    $(\"#diacriticInsensitiveMatchw\").show();\r\n");
      out.write("               }\r\n");
      out.write("               if (exactMatch >= 0 && diacriticInsensitiveMatch >=0)\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#exactMatchw\").show();\r\n");
      out.write("                    $(\"#diacriticInsensitiveMatchw\").show();\r\n");
      out.write("               }\r\n");
      out.write("               if (caseSensitiveMatch >= 0 && caseInsensitiveMatch >=0)\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#caseSensitiveMatchw\").show();\r\n");
      out.write("                    $(\"#caseInsensitiveMatchw\").show();\r\n");
      out.write("               }\r\n");
      out.write("               if (caseSensitiveSort >= 0 && caseInsensitiveSort >=0)\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#caseSensitiveSortw\").show();\r\n");
      out.write("                    $(\"#caseInsensitiveSortw\").show();\r\n");
      out.write("               }\r\n");
      out.write("               \r\n");
      out.write("               if ((combineCategoryBags >= 0 && (serviceSubset >=0 || bindingSubset  >=0)) ||\r\n");
      out.write("                       ((combineCategoryBags >= 0 || serviceSubset >=0) && bindingSubset  >=0) || \r\n");
      out.write("                       ((combineCategoryBags >= 0 ||  serviceSubset >=0) && bindingSubset  >=0) )\r\n");
      out.write("               {\r\n");
      out.write("                    $(\"#combineCategoryBagsw\").show();\r\n");
      out.write("                    $(\"#serviceSubsetw\").show();\r\n");
      out.write("                    $(\"#bindingSubsetw\").show();\r\n");
      out.write("               }\r\n");
      out.write("               \r\n");
      out.write("               return false;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          //src = http://stackoverflow.com/questions/1181575/javascript-determine-whether-an-array-contains-a-value\r\n");
      out.write("          var indexOf = function(needle) {\r\n");
      out.write("               if (typeof Array.prototype.indexOf === 'function') {\r\n");
      out.write("                    indexOf = Array.prototype.indexOf;\r\n");
      out.write("               } else {\r\n");
      out.write("                    indexOf = function(needle) {\r\n");
      out.write("                         var i = -1, index = -1;\r\n");
      out.write("\r\n");
      out.write("                         for (i = 0; i < this.length; i++) {\r\n");
      out.write("                              if (this[i] === needle) {\r\n");
      out.write("                                   index = i;\r\n");
      out.write("                                   break;\r\n");
      out.write("                              }\r\n");
      out.write("                         }\r\n");
      out.write("\r\n");
      out.write("                         return index;\r\n");
      out.write("                    };\r\n");
      out.write("               }\r\n");
      out.write("\r\n");
      out.write("               return indexOf.call(this, needle);\r\n");
      out.write("          };\r\n");
      out.write("\r\n");
      out.write("          var offset = 0;\r\n");
      out.write("          var maxrecords = 20;\r\n");
      out.write("          function search()\r\n");
      out.write("          {\r\n");
      out.write("               /*   \r\n");
      out.write("                $.each($('input:checkbox'), function(index,item){\r\n");
      out.write("                var itemname = item.name;\r\n");
      out.write("                if (item.checked)\r\n");
      out.write("                {\r\n");
      out.write("                fqs+=itemname+\",\";\r\n");
      out.write("                }\r\n");
      out.write("                });\r\n");
      out.write("                */\r\n");
      out.write("               //var fqs = $('input:checkbox').length ? $('input:checked').val() : '';\r\n");
      out.write("               //alert (fqs);\r\n");
      out.write("               var selection = $(\"#searchcriteria > button.btn.active\").val();\r\n");
      out.write("               //alert(selection);\r\n");
      out.write("\r\n");
      out.write("               //var findqualifier = $(\"#findqualifier\").val();\r\n");
      out.write("               //alert(findqualifier);\r\n");
      out.write("               var searchfor = $(\"#searchfor  > button.btn.active\").val();\r\n");
      out.write("               //alert(searchfor);\r\n");
      out.write("               var searchcontent = $(\"#searchcontent\").val();\r\n");
      out.write("               //alert(searchcontent );\r\n");
      out.write("               var url = 'ajax/search.jsp';\r\n");
      out.write("\r\n");
      out.write("               $(\"#collapseTwo\").collapse(\"show\");\r\n");
      out.write("               $(\"#collapseOne\").collapse(\"hide\");\r\n");
      out.write("\r\n");
      out.write("               var postbackdata = new Array();\r\n");
      out.write("\r\n");
      out.write("               postbackdata.push({\r\n");
      out.write("                    name: \"selection\",\r\n");
      out.write("                    value: selection\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("               postbackdata.push({\r\n");
      out.write("                    name: \"searchcontent\",\r\n");
      out.write("                    value: searchcontent\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("               postbackdata.push({\r\n");
      out.write("                    name: \"lang\",\r\n");
      out.write("                    value: $(\"#lang\").val()\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               $.each($('input:checkbox'), function(index, item) {\r\n");
      out.write("                    var itemname = item.name;\r\n");
      out.write("                    if (item.checked)\r\n");
      out.write("                    {\r\n");
      out.write("                         postbackdata.push({\r\n");
      out.write("                              name: \"findqualifier\",\r\n");
      out.write("                              value: itemname\r\n");
      out.write("                         });\r\n");
      out.write("                    }\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               postbackdata.push({\r\n");
      out.write("                    name: \"searchfor\",\r\n");
      out.write("                    value: searchfor\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("               postbackdata.push({\r\n");
      out.write("                    name: \"nonce\",\r\n");
      out.write("                    value: $(\"#nonce\").val()\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("               var request = $.ajax({\r\n");
      out.write("                    url: url,\r\n");
      out.write("                    type: \"POST\",\r\n");
      out.write("                    //  dataType: \"html\", \r\n");
      out.write("                    cache: false,\r\n");
      out.write("                    //  processData: false,f\r\n");
      out.write("                    data: postbackdata\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               request.done(function(msg) {\r\n");
      out.write("                    window.console && console.log('postback done ' + url);\r\n");
      out.write("\r\n");
      out.write("                    $(\"#resultdivs\").html(msg);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("               request.fail(function(jqXHR, textStatus) {\r\n");
      out.write("                    window.console && console.log('postback failed ' + url);\r\n");
      out.write("                    $(\"#resultdivs\").html(jqXHR.responseText + textStatus);\r\n");
      out.write("                    //$(\".alert\").alert();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("     </script>\r\n");
      out.write("\r\n");
      out.write("     ");
      out.write("<div class=\"modal hide fade container\" id=\"tmodelChooser\" tabindex=\"101\">\r\n");
      out.write("   <div class=\"modal-header\">\r\n");
      out.write("      <a href=\"javascript:$('#tmodelChooser').modal('hide');\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</a>\r\n");
      out.write("      <h3>");
      out.print(ResourceLoader.GetResource(session, "items.tmodel.chooser"));
      out.write("</h3>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("      <table class=\"table-bordered table-condensed\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("               <table>\r\n");
      out.write("                  <tr><td>");
      out.print(ResourceLoader.GetResource(session, "totals.records"));
      out.write("</td><td><span id=\"totalrecords\"></span></td></tr>\r\n");
      out.write("                  <tr><td>");
      out.print(ResourceLoader.GetResource(session, "totals.recordsreturned"));
      out.write("</td><td><span id=\"displayrecords\"></span></td></tr>\r\n");
      out.write("                  <tr><td>");
      out.print(ResourceLoader.GetResource(session, "totals.offset"));
      out.write("</td><td><span id=\"offset\">0</span></td></tr>\r\n");
      out.write("               </table>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <table>\r\n");
      out.write("                  <tr><td>");
      out.print(ResourceLoader.GetResource(session, "items.name"));
      out.write("</td><td><input type=\"text\" id=\"name_tmodel\" value=\"%\"></td></tr>\r\n");
      out.write("                  <tr><td>");
      out.print(ResourceLoader.GetResource(session, "items.lang"));
      out.write("</td><td><input type=\"text\" id=\"lang_tmodel\" value=\"\"></td></tr>\r\n");
      out.write("               </table>\r\n");
      out.write("            </td>\r\n");
      out.write("            \r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"javascript:pagedownChooserTmodel();\"><i class=\"icon-circle-arrow-left disabled icon-2x\" id=\"pageup\"></i></a>\r\n");
      out.write("      <a href=\"javascript:reloadTmodelModal();\"><i class=\"icon-refresh icon-2x\"></i></a>\r\n");
      out.write("      <a href=\"javascript:pageupChooserTmodel();\"><i class=\"icon-circle-arrow-right disabled icon-2x\" id=\"pagedown\"></i></a>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"tmodellist\">\r\n");
      out.write("         <img src=\"img/bigrollergreen.gif\" title=\"Loading\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("      <script src=\"js/tmodelsearch.js\"></script>\r\n");
      out.write("      <script src=\"js/tmodelChooser.js\"></script>\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("         $(\"#tmodelChooser\").keydown(function(e) {\r\n");
      out.write("            //if ($(\"#tmodelChooser\").dialog(\"isOpen\") === true)\r\n");
      out.write("            {\r\n");
      out.write("               if (e.which == 37) { // left\r\n");
      out.write("                  pagedownChooserTmodel();\r\n");
      out.write("               }\r\n");
      out.write("               else if (e.which == 39) { // right\r\n");
      out.write("                  pageupChooserTmodel();\r\n");
      out.write("               }\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("         $('.edit').editable(function(value, settings) {\r\n");
      out.write("            window.console && console.log(value + this + settings);\r\n");
      out.write("            reloadTmodelModal();\r\n");
      out.write("            //  RenderTmodelListBySearch('%', offset, maxrecords);\r\n");
      out.write("            return(value);\r\n");
      out.write("         }, {\r\n");
      out.write("            type: 'text',\r\n");
      out.write("            submit: i18n_ok\r\n");
      out.write("         });\r\n");
      out.write("         //only init the data when required reloadTmodelModal();\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"modal-footer\">\r\n");
      out.write("      <a href=\"#\" class=\"btn\" data-dismiss=\"modal\">");
      out.print(ResourceLoader.GetResource(session, "actions.cancel"));
      out.write("</a>\r\n");
      out.write("      <a href=\"javascript:$('#tmodelChooser').modal('hide');\" class=\"btn btn-primary\" data-dismiss=\"modal\">");
      out.print(ResourceLoader.GetResource(session, "actions.select"));
      out.write("</a>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");

//<a href="javascript:tModelCancel();" class="close" class="btn btn-danger">Cancel</a>
//<a href="javascript:tModelModal();" class="btn" >Pick a tModel</a>

      out.write("</div> <!-- /container -->\r\n");
      out.write("</form>\r\n");
      out.write("<div style=\"\r\n");
      out.write("     padding: 0px 0px 0px 0px; bottom: 0px; margin: 0px 0px 0px 0px; width:100%; text-align: center; position: fixed; \r\n");
      out.write("     background-color: white; \r\n");
      out.write("     \"><center><footer>v");

     out.write(StringEscapeUtils.escapeHtml(org.apache.juddi.v3.client.Release.getRegistryVersion()));
     
      out.write(" - <a href=\"http://www.apache.org\">");
      out.print(ResourceLoader.GetResource(session, "footer.apachecopyright"));
      out.write("</a>. \r\n");
      out.write("     ");
      out.print(ResourceLoader.GetResource(session, "items.nowconnectedto"));
      out.write(": \r\n");
      out.write("     ");
      out.print(StringEscapeUtils.escapeHtml(UddiHub.getInstance(application, session).getNodeName()) );
      out.write("</footer></center></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
